---
# macbook setup

-   hosts: mac
    roles:
        -   role: homebrew
            applications:
                - awscli
                - tmux
                - htop
                - terraform
                - jq
                - yarn
                - hub
                - make
                # Coreutils adds realpath among other things
                - coreutils
                - docker-credential-helper-ecr
                - zsh
                - zsh-completions
            casks:
                - jetbrains-toolbox
                - google-chrome
                - pop
                - spotify
                - discord
                - slack
                - spectacle
                - docker
                - zoom
                - loom

        -   role: ssh-keys
            github_key_title: "mbp.14-inch-retina-2021"
        -   role: karlmdavis.rcm-dotfiles
            rcm_user: "{{ lookup('env', 'USER') }}"
            rcup_bin: /usr/local/bin/rcup
            rcm_repos:
                -   repo: 'git@github.com:jnfry/dotfiles.git'
                    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/"
        -   role: use-zsh
        -   role: suzuki-shunsuke.nvm
            nvm_rc_path: "{{ ansible_env.HOME }}/.zsh"

